src/Entity/DepotAterme.php
<?php

namespace App\Entity;

use App\Repository\DepotAtermeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DepotAtermeRepository::class)]
class DepotAterme
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'NumCompte')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Individuelclient $compte = null;

    #[ORM\ManyToOne(inversedBy: 'peoduitep')]
    private ?ProduitEpargne $produit = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $datedepot = null;

    #[ORM\Column(length: 20)]
    private ?string $piececomptable = null;

    #[ORM\Column]
    private ?float $tauxinteret = null;

    #[ORM\Column]
    private ?int $periodemois = null;

    #[ORM\Column]
    private ?bool $is_interetcapitalise = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_echeance = null;

    #[ORM\Column]
    private ?float $valeurecheance = null;

    #[ORM\Column]
    private ?float $taxeretenue = null;

    #[ORM\Column]
    private ?float $retenuetaxe = null;

    #[ORM\Column]
    private ?float $TVA = null;

    #[ORM\Column]
    private ?bool $is_depotcall = null;

    #[ORM\Column]
    private ?bool $is_interetecheance = null;

    #[ORM\Column]
    private ?bool $is_interetmois = null;

    #[ORM\Column]
    private ?bool $is_interettrimestrielle = null;

    #[ORM\Column]
    private ?bool $is_interetsemestrielle = null;

    #[ORM\Column]
    private ?bool $is_interetpayelorscalcul = null;

    #[ORM\Column]
    private ?bool $_is_interettransferercptep = null;

    #[ORM\Column]
    private ?bool $is_retirealecheance = null;

    #[ORM\Column]
    private ?bool $is_remetreaucptalecheance = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompte(): ?Individuelclient
    {
        return $this->compte;
    }

    public function setCompte(?Individuelclient $compte): self
    {
        $this->compte = $compte;

        return $this;
    }

    public function getProduit(): ?ProduitEpargne
    {
        return $this->produit;
    }

    public function setProduit(?ProduitEpargne $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function getDatedepot(): ?\DateTimeInterface
    {
        return $this->datedepot;
    }

    public function setDatedepot(\DateTimeInterface $datedepot): self
    {
        $this->datedepot = $datedepot;

        return $this;
    }

    public function getPiececomptable(): ?string
    {
        return $this->piececomptable;
    }

    public function setPiececomptable(string $piececomptable): self
    {
        $this->piececomptable = $piececomptable;

        return $this;
    }

    public function getTauxinteret(): ?float
    {
        return $this->tauxinteret;
    }

    public function setTauxinteret(float $tauxinteret): self
    {
        $this->tauxinteret = $tauxinteret;

        return $this;
    }

    public function getPeriodemois(): ?int
    {
        return $this->periodemois;
    }

    public function setPeriodemois(int $periodemois): self
    {
        $this->periodemois = $periodemois;

        return $this;
    }

    public function isIsInteretcapitalise(): ?bool
    {
        return $this->is_interetcapitalise;
    }

    public function setIsInteretcapitalise(bool $is_interetcapitalise): self
    {
        $this->is_interetcapitalise = $is_interetcapitalise;

        return $this;
    }

    public function getDateEcheance(): ?\DateTimeInterface
    {
        return $this->date_echeance;
    }

    public function setDateEcheance(\DateTimeInterface $date_echeance): self
    {
        $this->date_echeance = $date_echeance;

        return $this;
    }

    public function getValeurecheance(): ?float
    {
        return $this->valeurecheance;
    }

    public function setValeurecheance(float $valeurecheance): self
    {
        $this->valeurecheance = $valeurecheance;

        return $this;
    }

    public function getTaxeretenue(): ?float
    {
        return $this->taxeretenue;
    }

    public function setTaxeretenue(float $taxeretenue): self
    {
        $this->taxeretenue = $taxeretenue;

        return $this;
    }

    public function getRetenuetaxe(): ?float
    {
        return $this->retenuetaxe;
    }

    public function setRetenuetaxe(float $retenuetaxe): self
    {
        $this->retenuetaxe = $retenuetaxe;

        return $this;
    }

    public function getTVA(): ?float
    {
        return $this->TVA;
    }

    public function setTVA(float $TVA): self
    {
        $this->TVA = $TVA;

        return $this;
    }

    public function isIsDepotcall(): ?bool
    {
        return $this->is_depotcall;
    }

    public function setIsDepotcall(bool $is_depotcall): self
    {
        $this->is_depotcall = $is_depotcall;

        return $this;
    }

    public function isIsInteretecheance(): ?bool
    {
        return $this->is_interetecheance;
    }

    public function setIsInteretecheance(bool $is_interetecheance): self
    {
        $this->is_interetecheance = $is_interetecheance;

        return $this;
    }

    public function isIsInteretmois(): ?bool
    {
        return $this->is_interetmois;
    }

    public function setIsInteretmois(bool $is_interetmois): self
    {
        $this->is_interetmois = $is_interetmois;

        return $this;
    }

    public function isIsInterettrimestrielle(): ?bool
    {
        return $this->is_interettrimestrielle;
    }

    public function setIsInterettrimestrielle(bool $is_interettrimestrielle): self
    {
        $this->is_interettrimestrielle = $is_interettrimestrielle;

        return $this;
    }

    public function isIsInteretsemestrielle(): ?bool
    {
        return $this->is_interetsemestrielle;
    }

    public function setIsInteretsemestrielle(bool $is_interetsemestrielle): self
    {
        $this->is_interetsemestrielle = $is_interetsemestrielle;

        return $this;
    }

    public function isIsInteretpayelorscalcul(): ?bool
    {
        return $this->is_interetpayelorscalcul;
    }

    public function setIsInteretpayelorscalcul(bool $is_interetpayelorscalcul): self
    {
        $this->is_interetpayelorscalcul = $is_interetpayelorscalcul;

        return $this;
    }

    public function isIsInterettransferercptep(): ?bool
    {
        return $this->_is_interettransferercptep;
    }

    public function setIsInterettransferercptep(bool $_is_interettransferercptep): self
    {
        $this->_is_interettransferercptep = $_is_interettransferercptep;

        return $this;
    }

    public function isIsRetirealecheance(): ?bool
    {
        return $this->is_retirealecheance;
    }

    public function setIsRetirealecheance(bool $is_retirealecheance): self
    {
        $this->is_retirealecheance = $is_retirealecheance;

        return $this;
    }

    public function isIsRemetreaucptalecheance(): ?bool
    {
        return $this->is_remetreaucptalecheance;
    }

    public function setIsRemetreaucptalecheance(bool $is_remetreaucptalecheance): self
    {
        $this->is_remetreaucptalecheance = $is_remetreaucptalecheance;

        return $this;
    }
}

src/Form/DepotAtermeType.php
<?php

namespace App\Form;

use App\Entity\DepotAterme;
use App\Entity\Individuelclient;
use App\Entity\ProduitEpargne;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DepotAtermeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('datedepot',DateType::class,[
                'widget'=>'single_text',
            ])
            ->add('piececomptable')
            ->add('tauxinteret')
            ->add('periodemois')
            ->add('is_interetcapitalise')
            ->add('date_echeance',DateType::class,[
                'widget'=>'single_text',
            ])
            ->add('valeurecheance')
            ->add('taxeretenue')
            ->add('retenuetaxe')
            ->add('TVA')
            ->add('is_depotcall')
            ->add('is_interetecheance')
            ->add('is_interetmois')
            ->add('is_interettrimestrielle')
            ->add('is_interetsemestrielle')
            ->add('is_interetpayelorscalcul')
            ->add('_is_interettransferercptep')
            ->add('is_retirealecheance')
            ->add('is_remetreaucptalecheance')
            ->add('compte',EntityType::class,[
                'class'=>Individuelclient::class,
                'choice_label'=>'nomclient',
                'by_reference'=>false,
            ])
            ->add('produit',EntityType::class,[
                'class'=>ProduitEpargne::class,
                'choice_label'=>'nomproduit',
                'by_reference'=>false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => DepotAterme::class,
        ]);
    }
}

src/Controller/Depotaterme/DepotAtermeController.php
<?php

namespace App\Controller\Depotaterme;

use App\Entity\DepotAterme;
use App\Form\DepotAtermeType;
use App\Repository\DepotAtermeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/depot/aterme')]
class DepotAtermeController extends AbstractController
{
    #[Route('/', name: 'app_depot_aterme_index', methods: ['GET'])]
    public function index(DepotAtermeRepository $depotAtermeRepository): Response
    {
        return $this->render('depot_aterme/index.html.twig', [
            'depot_atermes' => $depotAtermeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_depot_aterme_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DepotAtermeRepository $depotAtermeRepository): Response
    {
        $depotAterme = new DepotAterme();
        $form = $this->createForm(DepotAtermeType::class, $depotAterme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $depotAtermeRepository->add($depotAterme, true);

            return $this->redirectToRoute('app_depot_aterme_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('depot_aterme/new.html.twig', [
            'depot_aterme' => $depotAterme,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_depot_aterme_show', methods: ['GET'])]
    public function show(DepotAterme $depotAterme): Response
    {
        return $this->render('depot_aterme/show.html.twig', [
            'depot_aterme' => $depotAterme,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_depot_aterme_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, DepotAterme $depotAterme, DepotAtermeRepository $depotAtermeRepository): Response
    {
        $form = $this->createForm(DepotAtermeType::class, $depotAterme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $depotAtermeRepository->add($depotAterme, true);

            return $this->redirectToRoute('app_depot_aterme_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('depot_aterme/edit.html.twig', [
            'depot_aterme' => $depotAterme,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_depot_aterme_delete', methods: ['POST'])]
    public function delete(Request $request, DepotAterme $depotAterme, DepotAtermeRepository $depotAtermeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$depotAterme->getId(), $request->request->get('_token'))) {
            $depotAtermeRepository->remove($depotAterme, true);
        }

        return $this->redirectToRoute('app_depot_aterme_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/depot_aterme/_delete_form.html.twig
<form method="post" action="{{ path('app_depot_aterme_delete', {'id': depot_aterme.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ depot_aterme.id) }}">
    <button class="btn">Delete</button>
</form>

templates/depot_aterme/_form.html.twig
{{ form_start(form) }}
    {# {{ form_widget(form) }} #}
    <div style="padding:70px;">
        <div class="col" style="width:300px;">
            <div class="row">
                {{form_row(form.compte)}}
                {{form_row(form.produit)}}
                {{form_row(form.datedepot)}}
                {{form_row(form.piececomptable)}}
                {{form_row(form.tauxinteret)}}
                {{form_row(form.periodemois)}}
                {{form_row(form.is_interetcapitalise)}}
            </div>
        </div>

               <div class="col" style="width:300px;margin-left:350px;margin-top:-330px;">
            <div class="row">
                {{form_row(form.date_echeance)}}
                {{form_row(form.valeurecheance)}}
                {{form_row(form.taxeretenue)}}
                {{form_row(form.retenuetaxe)}}
                {{form_row(form.TVA)}}
                {{form_row(form.is_depotcall)}}
                {{form_row(form.is_interetecheance)}}
            </div>
        </div>

               <div class="col" style="width:300px;margin-left:700px;margin-top:-300px;">
            <div class="row">
                {{form_row(form.is_interetmois)}}
                {{form_row(form.is_interettrimestrielle)}}
                {{form_row(form.is_interetsemestrielle)}}
                {{form_row(form.is_interetpayelorscalcul)}}
                {{form_row(form._is_interettransferercptep)}}
                {{form_row(form.is_retirealecheance)}}
                {{form_row(form.is_remetreaucptalecheance)}}
    <button class="btn">{{ button_label|default('Save') }}</button>
            </div>
        </div>
    </div>
{{ form_end(form) }}

templates/depot_aterme/edit.html.twig
{{ include('header.html.twig') }}

{% block body %}
    <h1>Edit DepotAterme</h1>

    {{ include('depot_aterme/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_depot_aterme_index') }}">back to list</a>

    {{ include('depot_aterme/_delete_form.html.twig') }}
{% endblock %}

{{ include('footer.html.twig') }}

templates/depot_aterme/index.html.twig
{{ include('header.html.twig') }}

{% block body %}
    <h1>DepotAterme index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Datedepot</th>
                <th>Piececomptable</th>
                <th>Tauxinteret</th>
                <th>Periodemois</th>
                <th>Is_interetcapitalise</th>
                <th>Date_echeance</th>
                <th>Valeurecheance</th>
                <th>Taxeretenue</th>
                <th>Retenuetaxe</th>
                <th>TVA</th>
                <th>Is_depotcall</th>
                <th>Is_interetecheance</th>
                <th>Is_interetmois</th>
                <th>Is_interettrimestrielle</th>
                <th>Is_interetsemestrielle</th>
                <th>Is_interetpayelorscalcul</th>
                <th>_is_interettransferercptep</th>
                <th>Is_retirealecheance</th>
                <th>Is_remetreaucptalecheance</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for depot_aterme in depot_atermes %}
            <tr>
                <td>{{ depot_aterme.id }}</td>
                <td>{{ depot_aterme.datedepot ? depot_aterme.datedepot|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ depot_aterme.piececomptable }}</td>
                <td>{{ depot_aterme.tauxinteret }}</td>
                <td>{{ depot_aterme.periodemois }}</td>
                <td>{{ depot_aterme.isInteretcapitalise ? 'Yes' : 'No' }}</td>
                <td>{{ depot_aterme.dateEcheance ? depot_aterme.dateEcheance|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ depot_aterme.valeurecheance }}</td>
                <td>{{ depot_aterme.taxeretenue }}</td>
                <td>{{ depot_aterme.retenuetaxe }}</td>
                <td>{{ depot_aterme.TVA }}</td>
                <td>{{ depot_aterme.isDepotcall ? 'Yes' : 'No' }}</td>
                <td>{{ depot_aterme.isInteretecheance ? 'Yes' : 'No' }}</td>
                <td>{{ depot_aterme.isInteretmois ? 'Yes' : 'No' }}</td>
                <td>{{ depot_aterme.isInterettrimestrielle ? 'Yes' : 'No' }}</td>
                <td>{{ depot_aterme.isInteretsemestrielle ? 'Yes' : 'No' }}</td>
                <td>{{ depot_aterme.isInteretpayelorscalcul ? 'Yes' : 'No' }}</td>
                <td>{{ depot_aterme.isInterettransferercptep ? 'Yes' : 'No' }}</td>
                <td>{{ depot_aterme.isRetirealecheance ? 'Yes' : 'No' }}</td>
                <td>{{ depot_aterme.isRemetreaucptalecheance ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_depot_aterme_show', {'id': depot_aterme.id}) }}">show</a>
                    <a href="{{ path('app_depot_aterme_edit', {'id': depot_aterme.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="21">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_depot_aterme_new') }}">Create new</a>
{% endblock %}

{{ include('footer.html.twig') }}

templates/depot_aterme/new.html.twig
{{ include('header.html.twig') }}

{% block body %}
    <h1>Create new DepotAterme</h1>

    {{ include('depot_aterme/_form.html.twig') }}

    <a href="{{ path('app_depot_aterme_index') }}">back to list</a>
{% endblock %}

{{ include('footer.html.twig') }}

templates/depot_aterme/show.html.twig
{{ include('header.html.twig') }}

{% block body %}
    <h1>DepotAterme</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ depot_aterme.id }}</td>
            </tr>
            <tr>
                <th>Datedepot</th>
                <td>{{ depot_aterme.datedepot ? depot_aterme.datedepot|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Piececomptable</th>
                <td>{{ depot_aterme.piececomptable }}</td>
            </tr>
            <tr>
                <th>Tauxinteret</th>
                <td>{{ depot_aterme.tauxinteret }}</td>
            </tr>
            <tr>
                <th>Periodemois</th>
                <td>{{ depot_aterme.periodemois }}</td>
            </tr>
            <tr>
                <th>Is_interetcapitalise</th>
                <td>{{ depot_aterme.isInteretcapitalise ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Date_echeance</th>
                <td>{{ depot_aterme.dateEcheance ? depot_aterme.dateEcheance|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Valeurecheance</th>
                <td>{{ depot_aterme.valeurecheance }}</td>
            </tr>
            <tr>
                <th>Taxeretenue</th>
                <td>{{ depot_aterme.taxeretenue }}</td>
            </tr>
            <tr>
                <th>Retenuetaxe</th>
                <td>{{ depot_aterme.retenuetaxe }}</td>
            </tr>
            <tr>
                <th>TVA</th>
                <td>{{ depot_aterme.TVA }}</td>
            </tr>
            <tr>
                <th>Is_depotcall</th>
                <td>{{ depot_aterme.isDepotcall ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_interetecheance</th>
                <td>{{ depot_aterme.isInteretecheance ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_interetmois</th>
                <td>{{ depot_aterme.isInteretmois ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_interettrimestrielle</th>
                <td>{{ depot_aterme.isInterettrimestrielle ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_interetsemestrielle</th>
                <td>{{ depot_aterme.isInteretsemestrielle ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_interetpayelorscalcul</th>
                <td>{{ depot_aterme.isInteretpayelorscalcul ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>_is_interettransferercptep</th>
                <td>{{ depot_aterme.isInterettransferercptep ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_retirealecheance</th>
                <td>{{ depot_aterme.isRetirealecheance ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_remetreaucptalecheance</th>
                <td>{{ depot_aterme.isRemetreaucptalecheance ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_depot_aterme_index') }}">back to list</a>

    <a href="{{ path('app_depot_aterme_edit', {'id': depot_aterme.id}) }}">edit</a>

    {{ include('depot_aterme/_delete_form.html.twig') }}
{% endblock %}

{{ include('footer.html.twig') }}